-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

-- Note: This was tougher than expected! BigQuery doesn't have recursion or a way to natively loop so I had to find a formula for calculating Fibonacci's number for N. Used this: http://www.maths.surrey.ac.uk/hosted-sites/R.Knott/Fibonacci/fibFormula.html


with nums as
(select num from unnest(generate_array(1,100)) num)
,phis as (select (1+sqrt(5))/2 as phi, (1-sqrt(5))/2 as neg_phi)

select sum(fib)
from
(select num, cast(round((pow(phi,num+1)-pow(neg_phi,num+1))/sqrt(5),0) as numeric) fib
from nums,phis)
where mod(fib,2)=0 and fib<=4000000
